[tool.briefcase]
project_name = "Unit converter"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/unitconverter"
license = "BSD license"
author = 'Francis Jervoso'
author_email = "francis@example.com"

[tool.briefcase.app.unitconverter]
formal_name = "Unit conventer"
description = "this is unit converter"
icon = "src/unitconverter/resources/unitconverter"
sources = ['src/unitconverter']
requires = []


[tool.briefcase.app.unitconverter.macOS]
requires = []

[tool.briefcase.app.unitconverter.linux]
requires = []
system_requires = []

[tool.briefcase.app.unitconverter.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.unitconverter.iOS]
requires = []

[tool.briefcase.app.unitconverter.android]
requires = []
